# Site settings
title: Rebecca & Benigno
email: wedding@rebeccaandbenigno.com
url: http://www.rebeccaandbenigno.com
baseurl: ""
description: "Rebecca and Benigno are getting married!"

# Color settings (hex-codes without the leading hash-tag)
color:
  primary-dark: '#284d46'
  primary-light: '#fff'
  primary-accent: '#ffb400'
  links: '#ffb400'
  links-hover: '#ffb400'
  text-dark: '#393939'
  text-light: '#d3d3d3'

# Footer settings
footer: "Rebecca & Benigno"

# Social networks
social:

# Build
markdown: rdiscount
permalink: pretty
